name: runanonymous
description: Runanonymous - running pacer.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.0.0
  flutter_bloc: ^8.0.0
  cupertino_icons: ^0.1.3
  location: ^4.3.0
  flutter_localizations:
    sdk: flutter
  numberpicker: ^1.3.0
  intl: ^0.17.0
  equatable: ^0.6.0
  get_it: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
  bloc_test: ^9.0.1
  #test_coverage: ^0.5.0 <- left out due to dart version incompatibility. Will restore once dep updated.

flutter:
  uses-material-design: true
  assets:
    - assets/images/forest_bg.jpg
flutter_intl:
  enabled: true