name: runanonymous
description: Runanonymous - running pacer.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^6.0.3
  flutter_bloc: ^6.0.5
  cupertino_icons: ^0.1.3
  location: ^3.0.0
  screen: ^0.0.5
  audioplayers: ^0.17.0
  flutter_localizations:
    sdk: flutter
  numberpicker: ^1.3.0
  intl: ^0.16.1
  equatable: ^0.6.0
  get_it: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.0.0
  bloc_test: ^7.0.3
  test_coverage: ^0.4.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/forest_bg.jpg
    - assets/sounds/too_fast_clink.wav
    - assets/sounds/too_slow_whip.wav
flutter_intl:
  enabled: true